In [69]:
import pandas as pd
import numpy as np
from statsmodels.stats.correlation_tools import cov_nearest, corr_nearest

#### 3.1
Calculate near_psd covariance using testout_1.3.csv and testout_3.1.csv

In [70]:
# read input data
data1 = pd.read_csv('../testfiles/data/testout_1.3.csv')
data1

         x1        x2        x3        x4        x5
0  1.173986 -0.629631 -0.278932 -0.081448 -0.735140
1 -0.629631  1.318197  0.018090  0.446047  0.139309
2 -0.278932  0.018090  0.918102  0.360836  0.258613
3 -0.081448  0.446047  0.360836  0.894764 -0.235190
4 -0.735140  0.139309  0.258613 -0.235190  0.522607

In [71]:
def spectral_cov(cov, eps=1e-8):
    D = np.sqrt(np.diag(cov))
    corr = cov / np.outer(D, D)
    
    # eigen-decomposition
    eigval, eigvec = np.linalg.eigh(corr)

    # clip eigenvalues
    eigval_clipped = np.maximum(eigval, eps)

    # reconstruct corr matrix
    corr_psd = eigvec @ np.diag(eigval_clipped) @ eigvec.T

    # normalize
    corr_psd = corr_psd / np.outer(np.sqrt(np.diag(corr_psd)), np.sqrt(np.diag(corr_psd)))

    # corr to cov
    cov_psd = np.outer(D, D) * corr_psd
    
    return cov_psd

In [78]:
near_psd_cov = spectral_cov(data1)
pd.DataFrame(near_psd_cov)

          0         1         2         3         4
0  1.173986 -0.617989 -0.284559 -0.065152 -0.688287
1 -0.617989  1.318197  0.017092  0.445696  0.139176
2 -0.284559  0.017092  0.918102  0.354147  0.246056
3 -0.065152  0.445696  0.354147  0.894764 -0.218717
4 -0.688287  0.139176  0.246056 -0.218717  0.522607

#### 3.2
Calculate near_psd correlation using testout_1.4.csv and testout_3.2.csv

In [73]:
# read input data
data2 = pd.read_csv('../testfiles/data/testout_1.4.csv')
data2

         x1        x2        x3        x4        x5
0  1.000000 -0.483199 -0.241787 -0.067767 -0.714761
1 -0.483199  1.000000  0.015446  0.405660  0.178286
2 -0.241787  0.015446  1.000000  0.488250  0.336248
3 -0.067767  0.405660  0.488250  1.000000 -0.322136
4 -0.714761  0.178286  0.336248 -0.322136  1.000000

In [74]:
def spectral_corr(corr, eps=1e-8):
    # eigen-decomposition
    eigval, eigvec = np.linalg.eigh(corr)

    # clip eigenvalues
    eigval_clipped = np.maximum(eigval, eps)

    # reconstruct corr matrix
    corr_psd = eigvec @ np.diag(eigval_clipped) @ eigvec.T

    # normalize
    corr_psd = corr_psd / np.outer(np.sqrt(np.diag(corr_psd)), np.sqrt(np.diag(corr_psd)))
    
    return corr_psd

In [79]:
near_psd_corr = spectral_corr(data2)
pd.DataFrame(near_psd_corr)

          0         1         2         3         4
0  1.000000 -0.483199 -0.241787 -0.067767 -0.714761
1 -0.483199  1.000000  0.015446  0.405660  0.178286
2 -0.241787  0.015446  1.000000  0.488250  0.336248
3 -0.067767  0.405660  0.488250  1.000000 -0.322136
4 -0.714761  0.178286  0.336248 -0.322136  1.000000

#### 3.3
Calculate Higham covariance using testout_1.3.csv using testout_3.3.csv

In [76]:
higham_cov = cov_nearest(data1, method="higham")
higham_cov

/opt/anaconda3/lib/python3.13/site-packages/statsmodels/stats/correlation_tools.py:89: IterationLimitWarning:
Maximum iteration reached.

  warnings.warn(iteration_limit_doc, IterationLimitWarning)

array([[ 1.17398583, -0.62386998, -0.2943348 , -0.05767708, -0.6938878 ],
       [-0.62386998,  1.3181973 ,  0.01644917,  0.44857883,  0.14370287],
       [-0.2943348 ,  0.01644917,  0.91810185,  0.35406689,  0.24686647],
       [-0.05767708,  0.44857883,  0.35406689,  0.89476398, -0.21706217],
       [-0.6938878 ,  0.14370287,  0.24686647, -0.21706217,  0.52260731]])

#### 3.4
Calculate Higham correlation using testout_1.4.csv and testout_3.4.csv

In [80]:
higham_corr = corr_nearest(data2)
pd.DataFrame(higham_corr)

          0         1         2         3         4
0  1.000000 -0.483199 -0.241787 -0.067767 -0.714761
1 -0.483199  1.000000  0.015446  0.405660  0.178286
2 -0.241787  0.015446  1.000000  0.488250  0.336248
3 -0.067767  0.405660  0.488250  1.000000 -0.322136
4 -0.714761  0.178286  0.336248 -0.322136  1.000000